blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/techquestsdev/crontab-guru/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://github.com/techquestsdev/crontab-guru#readme
    about: Read the documentation for help and examples

